### PR TITLE
Remove custom GH_TOKEN

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Should work as well, right?

### CODE REVIEW

**Comment by casperdcl** [comment]
yeah but I kinda prefer the bot showing up as the releaser

image

**Review by casperdcl — COMMENTED** [review]
yeah but I kinda prefer the bot showing up as the releaser

image

**Review by casperdcl — APPROVED** [review]
be thee `:happiny:`

**Comment by 0x2b3bfa0** [comment]
`:staryu:`

**Pull request merged**
