### PR TITLE
Migrate from PyPI tokens to Trusted Publishers

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers#using-trusted-publishing-with-github-actions

### CODE REVIEW

**Review by casperdcl — APPROVED** [review]
thx!

**Comment by casperdcl** [comment]
image

> https://pypi.org/manage/project/shtab/settings/publishing

**Comment by 0x2b3bfa0** [comment]
@casperdcl, I don't have access to that page. Does it mean that it works correctly? 😅

**Comment by 0x2b3bfa0** [comment]
Sounds tempting, but I currently have to rotate 275 GitHub Actions secrets. 🙈 I'll get to it later this month, if you don't do it first. `:slaking:`

**Comment by casperdcl** [comment]
I'm a bit shocked that it really should be 4-ish lines. It's amazing how much @EnterpriseQualityCoding can be condensed :)

**Pull request merged**
