### PR TITLE
bash: support -- delimeter

### LINKED ISSUE #163: Complete only positional arguments after double dash ("--")
All arguments following "--" in argparse are treated as positional arguments. 
e.g.
```shell
compgen -W "foo bar baz" -- b
```
As far as I can tell shtab doesn't treat double dash in a special manner.
It would be pretty nice if shtab recognized this as delimiter between the options and the positional arguments.

I couldn't find a reference to this behavior in argparse documentation, but it's evident from [code ](https://github.com/python/cpython/blob/3.12/Lib/argparse.py#L1961)& usage.
```python
for i, arg_string in enumerate(arg_strings_iter):  
  # all args after -- are non-options
  if arg_string == '--':
...
```

This is a common practice, as can be seen in POSIX:
> ## POSIX.1–2017 standard
> 12.2 [Utility Syntax Guidelines](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)

> ### Guideline 10:

> The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the ‘-’ character.

it solves some ambiguity when using optional arguments that accept multiple values.
```shell
git checkout master     # Checkout the master branch
git checkout -- master  # Checkout the file named master
rm -- -file.txt  # delete file with dash in name 
```
By taking double dash into account, cases such as above would be completed correctly.

### PR DESCRIPTION
**Pull request by casperdcl**
- fixes #163

[`diff` *sans* whitespace](https://github.com/iterative/shtab/pull/164/files?w=1)

### CODE REVIEW

**Comment by casperdcl** [comment]
/CC @usidedown does this work for you?

```sh
pip install "git+https://github.com/iterative/shtab.git@double-dash#egg=shtab"
```

**Comment by usidedown** [comment]
> /CC @usidedown does this work for you?
> 
> ```shell
> pip install "git+https://github.com/iterative/shtab.git@double-dash#egg=shtab"
> ```

**Comment by usidedown** [comment]
Awesome, thanks for the quick response!

I'm getting a slight weirdness.

Here's my example:
```python
import argparse

def get_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--opt1', choices=['a','b'])
    parser.add_argument('pos1', type=int, choices=list(range(8)))
    parser.add_argument('pos2', type=int, choices=list(range(4)))
    parser.add_argument('pos3', type=int, choices=list(range(2)))
    return parser


def main():
    parser = get_parser()
    print(parser.parse_args())

if __name__ == '__main__':
    main()
```

my completion commandline:
```shell
eval "$(shtab src.test.get_parser --prog=foo --shell=bash)"
```

If I do the regular
```shell
foo 6 4 <tab>
```
I get `0 1` choices as expected.
But if I do
```shell
foo -- 6 4 <tab>
```
I get `0 1 2 3` completions

**Comment by casperdcl** [comment]
try now?

**Comment by usidedown** [comment]
> try now?

Looks good!
Even managed to complete a file starting with - (not possible without --)

**Pull request merged**
